# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50355e2ad58b954279fc426b3255dea97bc3330f6d6468695aec726ea9772bea55ca45ee7b68744f1f080800de27bb9f37da63ad8438bbccd168066f7d434540

test:
  secret_key_base: 8182771a1ac00c66c24be678ce2f9a3f20421c79254b554e9187b5ae24bdde3f1511d7866c1c49b227a3b6004958a822fbec559094972d3680cdb29f1e2b66b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
